### PR TITLE
Add support for generating viewmodels w/ controllers

### PR DESCRIPTION
**Pull request by mheap**

### CODE REVIEW

**Comment by WanWizard** [comment]
@philsturgeon want to implement this?

**Comment by philsturgeon** [comment]
I don't know enough about ViewModels to know if thats any good.

**Comment by WanWizard** [comment]
Ok. If you're not against it, I will add it to 1.3/develop.

**Comment by philsturgeon** [comment]
+0 :)

Emailing from my iPhone 4S like a BOSS!

**Pull request closed without merging**
