### PR TITLE
Support --module option to oil generate scaffold and admin

### PR DESCRIPTION
**Pull request by kenjis**
`oil g scaffold <modelname> ... --module=<modulename>`
`oil g admin <modelname> ... --module=<modulename>`

### CODE REVIEW

**Comment by WanWizard** [comment]
any change you can update this? It can't be merged automatically anymore.

**Comment by kenjis** [comment]
I did `rebase 1.8/develop`. Can you?

**Comment by WanWizard** [comment]
are there docs for this?

**Comment by sagikazarmark** [comment]
It would be awesome to do the same for model, migration, etc generation and not just for modules, but packages as well.

**Comment by kenjis** [comment]
Sorry, I found that a generated file is broken. I'll check and fix.

**Pull request closed without merging**
