### PR TITLE
Allow a Cli option to set the folder to which the package should be installed

### PR DESCRIPTION
**Pull request by axelitus**
Allow a Cli option to set the folder to which the package should be installed. Usage: php oil install package-dummy folder=superb. That way the Package Repo Name is isolated from the actual Package Name, thus allowing other sources to name their packages as they see fit.

Example:
I name my package repos like 'fuel-pkg-dummy' to identify them as packages (apps would be named like 'fuel-app-cool'). As of now if I add my github account as source and try to install the Dummy Package, it gets installe to pkg-dummy, which is wrong. So with this changes I could run 'php oil install pkg-dummy folder=dummy' and it would get installed to the dummy folder, which is correct.

This relates to the Pull Request for 1.0/develop https://github.com/fuel/oil/pull/44

### CODE REVIEW

**Comment by philsturgeon** [comment]
The feature you provide does not match up with the description provided.

Besides the naming of your repo is no longer important and the sources are no longer relevant as only one source now exists: cells.fuelphp.com.

The scope of this change seems to be to get package to install to wherever, but does that need to happen? Are people running multiple package directories, and if so why?

Normally a change needs to explain what the current problem is and why it needs to happen, but as your explanation doesnt match its hard for me to see your thinking :)

**Comment by axelitus** [comment]
Ok I think I typed it the wrong way :P let me try to clarify this:
The option is not for the \Cli class, but for the Oil\Cell class install() method, but not to be given as a normal method parameter, but gathering it through the \Cli::option() function (as is the version option).

This was discussed in the IRC #fuelphp channel, and I did state the point whether this would make sense taking into account the new cells.fuelphp.com development for package publishing. It was said that regarding the cells.fuelphp.com, 'alternate' package sources will still be a supported feature (if I understood correctly). So let me explain with an example why this has been done:

I have several repos on GitHub (mostly if not all of them using fuel). I plan on posting packages, as well as full apps on GitHub, thus I want to identify them with a 'prefix' like: 'fuel-pkg-MyAwesomePackage' and 'fuel-app-MyAwesomeApp'. Now, the packages in the fuel-packages GitHub account do make sense as to only having the 'fuel-' prefix, as they are all packages; but not in my case.

So, having package sources added in the config file (in my case https://github.com/axelitus) and trying to install a package using oil, it gets installed in a folder named 'pkg-MyAwesomePackage' because the oil install command only takes into account the 'fuel-' prefix, so to install to that folder would be wrong because the package would not work as it needs to be installed to a folder with name: 'MyAwesomePackage' inside the packages. So with this changes I could run 'php oil install pkg-MyAwesomePackage folder=MyAwesomePackage' to tell oil it should use the 'MyAwesomePackage' folder instead of the package name as the install folder name and thus it would be in the correct path.

So if no other source will be allowed when using oil but cells.fuelphp.com, then this should be forgotten as it only makes sense with multiple 'alternate' sources.

**Comment by philsturgeon** [comment]
There is no need for this, prefixes don't matter at all anymore and the package is installed with whatever name the developer intended regardless of the repo name.

**Comment by axelitus** [comment]
Ok then, if that's the case this pull request can be closed as it makes no sense at all within the new packages workflow. Looking forward to the new cells.fuelphp.com 'Packages Market' :D do you have an estimated release date?

**Pull request closed without merging**
