### PR TITLE
Add support for phpunit exclude-group option

### PR DESCRIPTION
**Pull request by aronrosenberg**

### CODE REVIEW

**Comment by WanWizard** [comment]
Could you also update the oil documentation with these new options you've been adding?

**Comment by aronrosenberg** [comment]
Where do I update the docs? Didn't find it inline in the code.

**Comment by aronrosenberg** [comment]
Made a pull request to fuel/docs which now documents the oil test command

**Comment by aronrosenberg** [comment]
The doc's have now been updated with the changes this makes, so this can be merged.

**Comment by WanWizard** [comment]
eh, no. This pull request is against 1.3/develop, but 1.3 has been released so we don't accept pull requests on it any more.

**Pull request closed without merging**
