### PR TITLE
Package generation added

### PR DESCRIPTION
**Pull request by sagikazarmark**
I added package generation to oil.

Usage:
use --vsc or -v to create composer.json and README.md
use --path or -p to add your custom path (MUST be included in package_paths)
use --drivers or -d to create a driver-based package
use --drivers/-d=driver1,driver2 to create default drivers

### CODE REVIEW

**Comment by sagikazarmark** [comment]
Ok, I wait for the end. :) No more push.

**Comment by WanWizard** [comment]
found one more, and that's it I think. Can you also add this to the docs?

**Comment by sagikazarmark** [comment]
Of course.

**Comment by sagikazarmark** [comment]
PR for docs sent

**Pull request merged**
