### PR TITLE
Updated wording of help text to match other help text.

### PR DESCRIPTION
**Pull request by aranw**
Dead simple change. 

Confused me at first while using the command and thought it would be best if it matched all other help text.

### CODE REVIEW

**Comment by philsturgeon** [comment]
It doesn't matter which you use (if either) and cells are not even enabled yet anyway.

Which should we suggest in the help text? Flip a coin!

**Comment by aranw** [comment]
Think which ever gets used should be the same throughout, if you were describing them to someone what would you use? 

Cells? or a Cell?

**Comment by philsturgeon** [comment]
Depends, you list cells and work with cells but you want to see informaton about a cell.

You install a cell, but collectively you are working with cells. :-/

**Comment by aranw** [comment]
I think Cell is probably best usage within the Oil application

**Pull request merged**
