### PR TITLE
Feature/new magic migrations

### PR DESCRIPTION
**Pull request by zbrox**
I've added two missing but specified in the docs magic migrations.
One is add_{fieldname}_to_{tablename} and the other is rename_field_{table}_{fieldname}_to_{fieldname}.
I wasn't sure about how to specify the table name in the latter, because in the docs the magic migration is specified as rename_field_{fieldname}_to_{newfieldname}, so I added the tablename before the fieldname.
Hope this is helpful.

### CODE REVIEW

**Comment by philsturgeon** [comment]
Thanks a LOT for this, I have been putting it off for a while. Not so sure on the latter though, maybe:  `rename_field_<field>_to_<field>_in_<table>`?

**Comment by zbrox** [comment]
I really wasn't sure about the syntax of the second one. I think your proposition is better. I can rework it like this this weekend.

**Comment by philsturgeon** [comment]
Cool. Let me know what/when amd I'll hit the big green "Merge" button.

**Comment by zbrox** [comment]
The syntax for the rename field magic migration is now `rename_field_<field>_to_<field>_in_<table>`. I've tested it  but could you have a look, since I just got home and I've had a couple of pints and some gin with some oddly coloured liquor in it.
Hope this is helpful.

**Comment by zbrox** [comment]
I just added the down action for the drop table magic migration. I am not sure if this is the best way, because with DB::list_columns I can't differentiate the different types of indexes. A normal index and a fulltext one are both listed as MUL. Anyway the down action should add properly the data types of the fields of the dable, their default values, primary keys and indexes.
If you can give me hints on a better implementation I'll be more than happy to rework this :)

**Comment by zbrox** [comment]
I'm sorry to spam the discussion. Just wanted to mention that adding or dropping multiple columns resulted in mysql errors due to the DBUtil class. I've fixed that and made a pull request to core.

**Comment by zbrox** [comment]
I forgot to mention that the multiple fields pull request has been merged to the core, so this should be working fine now even with multiple fields for adding/dropping.

**Pull request merged**
