### PR TITLE
Remove everything about oil cell command

### PR DESCRIPTION
**Pull request by findrakecil**
## Summary

Because `cell` command is not going through production, I have removed `cell` command from this repo

## Issues

See this issue #266 for more information

### CODE REVIEW

**Comment by WanWizard** [comment]
Thanks. Would you mind removing it from the docs too?

**Comment by findrakecil** [comment]
You're welcome

But, pardon me. I couldn't find any documentation about `cell` command. I've checked in `fuel/docs` repository on branch `1.9/develop` and I didn't find anything about it.

Could you tell me on which docs I should remove?

**Comment by WanWizard** [comment]
Possible, it could well be it was already removed in the past, or (more likely) never documented by Phil. In that case, job done. ;-)

**Comment by findrakecil** [comment]
I see. I guess it's okay to merge this PR then 😄
I'll make another PR if I found anything about `cell` command

**Pull request merged**
