### PR TITLE
Generate TASK templates

### PR DESCRIPTION
**Pull request by zerojarvis**
Added this so that I could generate TASK skeletons quickly so I can build "script" tasks.

### CODE REVIEW

**Comment by zerojarvis** [comment]
Tested the generator works.

oil g task -f exampletask task1 task2 task3 task4
oil r exampletask
oil r exampletask:task1

**Comment by WanWizard** [comment]
Can you document this new functionality?

**Comment by WanWizard** [comment]
Related to #145

**Comment by WanWizard** [comment]
Code didn't run. Did you test this?

**Pull request merged**
