### PR TITLE
Updated login check which caused infinite loop.

### PR DESCRIPTION
**Pull request by aranw**

### CODE REVIEW

**Comment by jschreuder** [comment]
This makes no sense. It used to say: "when auth checks out redirect to the admin", now it says "when auth checks out do nothing, when it doesn't redirect to admin"...?

**Comment by philsturgeon** [comment]
Ahh yes, `Auth::check() or`

**Comment by aranw** [comment]
I don't know that line was causing my browser to loop infinitely. 

I switched it round like that and now it works fine...

**Comment by aranw** [comment]
`Auth::check() or` also causes infinite loops.

**Comment by philsturgeon** [comment]
You just disabled it, not fixed it. This is basically saying "If you are 
already logged in then dont bother trying to log in again".

**Comment by philsturgeon** [comment]
Push! :)

Emailing from my iPhone 4S like a BOSS!

**Comment by WanWizard** [comment]
Sorry, not compliant with the coding standards. 

The "if" needs a space before the bracket, and it needs braces, which should be put on a new line...

**Comment by aranw** [comment]
Sorry Fixed :-)

**Comment by WanWizard** [comment]
Sorry again. ;)

"and it needs braces, which should be put on a new line..."

**Comment by aranw** [comment]
Sorted it.

**Comment by jschreuder** [comment]
Did this fix anything? With the old code the redirect was only executed when `Auth::check()` returns true, with the new code it's exactly the same - just more verbose.

**Comment by aranw** [comment]
Well I don't have a infinite loop?

**Comment by aranw** [comment]
Previously it was `Auth::check() and Response::redirect('admin');` 

Which basically all it did was : 
1. Check if user logged in
2. Then redirect

Now the code does : 
1. Check if user logged in
2. If logged in redirect
3. If not continue

**Comment by jschreuder** [comment]
The code will act exactly the same as the old code under every condition, the problem probably lay elsewhere.

If you don't understand why a code change fixes something the problem most often lies elsewhere and you're either introducing a bug-workaround instead of a fix or just a random bit of code that does nothing. In this case it looks to me like the latter.

**Comment by aranw** [comment]
Well sorry I tried to fix something. Good Bye.

**Comment by jschreuder** [comment]
Ah, you don't understand how boolean operators are parsed.

For `and` the righthand side is only executed when the lefthand side evaluated to true. Thus `left() and right()` will only call on `right()` if `left()` evaluated to a true value, in fact meaning `if (left()) { right(); }`. Thus what you changed it too, with no semantic change.

`or` works likewise but only executes when the lefthand side executed to false, thus `left() or right()` means `if ( ! left()) { right(); }`

Both are very logical and common to almost all programming languages as they're not only usefull but also a language optimization: `and` can't evaluate to true if the first condition is already false, no reason to check the second. For `or` the whole statement is already true if the first condition is true, no reason to check the second anymore.

**Comment by aranw** [comment]
So why didn't you say that rather than being rude?

**Comment by jschreuder** [comment]
> Well sorry I tried to fix something. Good Bye.

Don't take this the wrong way, I'm just critical of fixes if I don't see them doing anything usefull. Something you should be glad of as our critical eye on things like these impacts the quality of the whole framework.

**Comment by aranw** [comment]
Yes but think you should be more grateful of users **trying** to contribute and try to be constructive in your reply rather than rude.

**Comment by jschreuder** [comment]
> So why didn't you say that rather than being rude?
> 
> Yes but think you should be more grateful of users **trying** to contribute and try to be constructive in your reply rather than rude. 

I didn't mean to come across as rude. I asked you "why" this change would fix it, to which you replied that this resulted in your code not looping anymore - leaving out the important **why** it fixed it. Which is a very important distinction and thus I made the assumption that you didn't know why it fixed it, maybe a wrong assumption in which case I'm still interested to hear why I'm wrong. Maybe I'm wrong, but I do want to hear **why** - just telling me it works like this isn't enough.

That's meant as constructive critisism, not meaning to call you dumb or being ungrateful. I won't be afraid to question a "fix" in fear of being considered "ungrateful", that's part of my job as one of the devs overseeing this project.

**Comment by LTheobald** [comment]
A little off topic but when I had a FuelPHP redirect loop issue, my Google searches lead me to this pull request a few times.  Hopefully pointing out my stupid mistake will help the next person who does the same thing :)

The original poster seemed to have an issue where the controller was bouncing back from admin to admin_login and back again repeatedly until the browser gave up.  I was having the same issue and trying to track it down.  For me, the problem was that I had changed my SimpleAuth groups so that the Admin group now had a level of 10, not 100.  But in the Admin controller, there is a line specifically checking the login for a group level of 100.  Due to this, it's failing the login.  So the solution for now - leave the admin group at a level of 100.

**Comment by AddoSolutions** [comment]
Is anyone still experiencing problems here?

**Comment by WanWizard** [comment]
A quick dive into the oil templates show that there are three admin controller views: admin-orm, admin-crud and scaffold-crud. All three seem to take a different approach on how to handle the login with a non-admin user.

Which of the three did you generate?

**Comment by WanWizard** [comment]
@AddoSolutions can you check if this fixes it?

**Comment by AddoSolutions** [comment]
I followed this tutorial (which is probably out of date):
http://net.tutsplus.com/tutorials/php/build-an-admin-panel-with-the-fuel-php-framework/

After adding a users model, I ran this:
oil generate admin posts title:string slug:string summary:text body:text user_id:int

After digging into it, I commented out (on line 21 of /fuel/app/classes/controller/admin.php): Response::redirect('admin/login');

That fixed it, I also was able to fix it by moving the login controller from Controller_Admin to a seperate Controller_Admin_Login.  Probably pretty n00bish, but it works :)

Great work on this framework guys!

**Pull request merged**
